FROM ubuntu:22.04

#Install SSH
RUN apt-get update
RUN apt-get -y install openssh-server
EXPOSE 22
RUN systemctl enable sshd
RUN systemctl start sshd

#Add user
RUN useradd -m w.rose 
RUN echo 'w.rose:followthewhiterabbit' | chpasswd
RUN echo 'root:B10L4BShutd0wn123!' | chpasswd

#Download script
RUN wget http://10.177.200.71/CyberCity/challenges/Biolab_Shutdown/shutdown.sh -o /biolab-rebootSequence.sh
RUN chown root:root /biolab-rebootSequence.sh
RUN chmod 700 /biolab-rebootSequence.sh

