FROM ubuntu:22.04

#Install SSH
RUN apt-get install openssh-server
RUN systemctl enable sshd
RUN systemctl start sshd

#Add user
RUN useradd -m w.rose 
RUN chpasswd w.rose:followthewhiterabbit
RUN chpasswd root:B10L4BShutd0wn123!

#Download script
RUN wget http://10.177.200.71/CyberCity/Challenge_Files/biolabShutdown/shutdown.sh -o /biolab-rebootSequence.sh

